### ISSUE TITLE
.Net Core + GTK3

### ISSUE THREAD

**Issue by OmidID** [jsuarezruiz/forms-gtk-progress#10]
Do you have any plan to upgrade it and use new technologies ?
Here we have 2 kind of hardwares, ARM without NEON and new hardware ARM with NEON
We are using XF and GTK# for backend for both devices. But we are looking for a way to use .Net Core on New hardware to have better performance.

**Comment by jsuarezruiz** [comment]
Soon the backend will use an official gtk sharp 2.12 NuGet package. Currently everything works on Windows, macOS and Linux although you must install gtk sharp on each system and add references by hand. The NuGet package will avoid steps and possibly problems. As soon as we have the GTK3 bindings completed at the official level (official NuGet, etc), we will propose to update the Xamarin.Forms GTK backend to version 3. Meanwhile, it is based on version 2.12.
