### ISSUE TITLE
Cannot get Xamarin Forms GTK dev package from Myget

### ISSUE THREAD

**Issue by RogerHardiman** [jsuarezruiz/forms-gtk-progress#8]
I have used the GTK preview on some projects.

The MyGet Xamarin Forms package with the GTK preview has gone.
(https://www.myget.org/F/xamarinforms-dev/api/v3/index.json)

Has it been replaced by something else?

**Comment by jsuarezruiz** [comment]
Thanks for use it!.
You can find the latest one in Xamarin.Forms Nightly: [https://www.myget.org/F/xamarinforms-ci/api/v2](https://www.myget.org/F/xamarinforms-ci/api/v2)

**Comment by jsuarezruiz** [comment]
Also available in NuGet directly.
