### ISSUE TITLE
Can we add native menus to Xamarin.Forms gtk application?

### ISSUE THREAD

**Issue by winffee** [jsuarezruiz/forms-gtk-progress#9]
Hi,

Can we build a GTK app with native windows menus(like vs menus: FIles,Edit,View)?  I didn't find any `Gtk.Application.SetAppMenu` method or something like that.

Thanks in advance.

Elvis Xia

**Comment by jsuarezruiz** [comment]
Of course you can. But you would have to create a Custom Renderer. I have a FormsGT Toolkit: [https://github.com/jsuarezruiz/FormsGtkToolkit](https://github.com/jsuarezruiz/FormsGtkToolkit ) trying to add more GTK Widgets, there are no menus yet, but I take note.
